jobs:
- job: Lin
  # About 150% of total time
  timeoutInMinutes: 85
  pool:
    name: LIN_VMSS_VENV_F8S_WU2
  variables:
    system.debug: true
    WORKERS_NUMBER: 8
    BUILD_TYPE: Release
    REPO_DIR: $(Build.Repository.LocalPath)
    WORK_DIR: $(Pipeline.Workspace)/_w
    BUILD_DIR: $(WORK_DIR)/build
    BIN_DIR: $(REPO_DIR)/bin/intel64/$(BUILD_TYPE)
  steps:
  - checkout: self
    clean: true
    fetchDepth: 1
    lfs: false
    submodules: recursive
    path: openvino
  - script: |
      curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2019-06-01"
      whoami
      uname -a
      which python3
      python3 --version
      gcc --version
      lsb_release
      env
      cat /proc/cpuinfo
      cat /proc/meminfo
      vmstat -s
      df
    displayName: 'System info'
  - script: |
      rm -rf $(WORK_DIR) ; mkdir $(WORK_DIR)
      rm -rf $(BUILD_DIR) ; mkdir $(BUILD_DIR)
    displayName: 'Make dir'
  - script: |
      sudo apt --assume-yes install libusb-1.0-0-dev
      python3 -m pip install -r ./inference-engine/ie_bridges/python/requirements.txt
      # For running Python API tests
      python3 -m pip install -r ./inference-engine/ie_bridges/python/src/requirements-dev.txt
    displayName: 'Install dependencies'
  - script: |
      wget https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-linux.zip
      unzip ninja-linux.zip
      sudo cp -v ninja /usr/local/bin/
    workingDirectory: $(WORK_DIR)
    displayName: 'Install Ninja'
  - task: CMake@1
    inputs:
      # CMake must get Python 3.x version by default
      cmakeArgs: -GNinja -DVERBOSE_BUILD=ON -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) -DENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DENABLE_TESTS=ON $(REPO_DIR)
      workingDirectory: $(BUILD_DIR)
  - script: ninja
    workingDirectory: $(BUILD_DIR)
    displayName: 'Build Lin'
  - script: ls -alR $(REPO_DIR)/bin/
    displayName: 'List files'
  - script: $(BIN_DIR)/unit-test --gtest_print_time=1 --gtest_filter=-backend_api.config_unsupported:*IE_GPU*
    displayName: 'nGraph UT'
    continueOnError: false
  - script: $(BIN_DIR)/InferenceEngineUnitTests --gtest_print_time=1
    displayName: 'IE UT old'
    continueOnError: false
  - script: $(BIN_DIR)/ieUnitTests
    displayName: 'IE UT'
    continueOnError: false
  - script: $(BIN_DIR)/cpuUnitTests
    displayName: 'CPU UT'
    continueOnError: false
  - script: $(BIN_DIR)/gnaUnitTests
    displayName: 'GNA UT'
    continueOnError: false
  - script: $(BIN_DIR)/vpuUnitTests
    displayName: 'VPU UT'
    continueOnError: false
  - script: $(BIN_DIR)/ieFuncTests
    displayName: 'IE FuncTests'
    continueOnError: false
  - script: $(BIN_DIR)/cpuFuncTests --gtest_print_time=1
    displayName: 'CPU FuncTests'
    continueOnError: false
  - script: $(BIN_DIR)/MklDnnBehaviorTests
    displayName: 'MklDnnBehaviorTests'
    continueOnError: false
  - script: |
      git clone https://github.com/openvinotoolkit/testdata.git
      git clone https://github.com/google/gtest-parallel.git
    workingDirectory: $(WORK_DIR)
    displayName: 'Clone testdata & gtest-parallel'
  - script: |
      export DATA_PATH=$(WORK_DIR)/testdata
      export MODELS_PATH=$(WORK_DIR)/testdata
      python3 $(WORK_DIR)/gtest-parallel/gtest-parallel $(BIN_DIR)/MklDnnFunctionalTests --workers=$(WORKERS_NUMBER) --print_test_times --dump_json_test_results=MklDnnFunctionalTests.json -- --gtest_print_time=1
    workingDirectory: $(WORK_DIR)
    displayName: 'MklDnnFunctionalTests'
    continueOnError: false
  - script: |
      export DATA_PATH=$(WORK_DIR)/testdata
      export MODELS_PATH=$(WORK_DIR)/testdata
      $(BIN_DIR)/InferenceEngineCAPITests
    displayName: 'IE CAPITests'
    continueOnError: false
  - script: |
      export DATA_PATH=$(WORK_DIR)/testdata
      export MODELS_PATH=$(WORK_DIR)/testdata
      export LD_LIBRARY_PATH=$(BIN_DIR)/lib
      export PYTHONPATH=$(BIN_DIR)/lib/python_api/python3.6
      env
      cd $(REPO_DIR)/inference-engine/ie_bridges/python/tests
      pytest
    displayName: 'Python API Tests'
    continueOnError: false
    enabled: false

